### ISSUE TITLE
No Issue, just a question:  How to transmit a radio stream to a bluetooth speaker

### ISSUE THREAD

**Issue by chess-levin** [renatoianhez/Lolin32-radio#1]
Hello @renatoianhez ,
thank you for sharing your excellent work here on github!

I've recently built my own web radio based on this projects 

* https://github.com/schreibfaul1/ESP32-audioI2S/tree/master/examples/Better_WiFi_throughput
* https://github.com/schreibfaul1/ESP32-MiniWebRadio

I had troubles to get a smooth, uninterrupted audio experience unless I found the previously mentioned code/project. The TCP-stream broke down every now and then. So I had to reconfigure the TCP-Settings used by the Arduino framework.

Now the receiving part is fine, but I'm missing a way to transmit the sound to one of my Bluetooth speakers. As a workaround I bought a TX/RX-Transceiver (amazon) that converts the analogue lineout-signal and sends it via Bluetooth to a speaker. Obviously it is nuts, to first send the audio stream through a DAC + a class D amp and afterwards convert it back to a digital signal. So your project seems to be a solution to this problem.

During my research I found several sources that were saying, ESP32 is not good for transmitting audio via BT. I was wondering if receiving a audio-stream via TCP and sending audio via BT in parallel is a problem that causes interrupted sound and therefore a bad listening experience.

Maybe you could share some deeper information on your BT solution and about the sound quality.

As far as I understand you use BT as an input source and not as an output sink - correct?

Thank you very much in advance!

**Comment by renatoianhez** [comment]
Yes! The Bluetooth function on my radio (when selected on a rear button) is only the reception of the signal generated by another device, such as a cell phone playing music via Spotify. In this case, the radio function is switched off. 
Perhaps, in your case, a small dedicated Bluetooth transmission board like [this one](https://pt.aliexpress.com/item/1005005777451417.html) will be the solution to take the audio signal and transmit it.
I believe that transmitting data simultaneously with receiving stream data is also possible using different cores in the ESP32 that are dual core (it would not be possible in the ESP32 C3, for example). However, I don't really understand how to dedicate a task to a specific core. In the [Wolle's audio library](https://github.com/schreibfaul1/ESP32-audioI2S) there are some clues on how to do this.

**Comment by chess-levin** [comment]
Tank you for answering my question.
I already ordered this KCX_BT_EMITTER, but as I wrote overall this results in an odd signal chain.
So I'm going to ask pschatzman the author of [audio-tools](https://github.com/pschatzmann/arduino-audio-tools/tree/main), if he could give me tome tips, to get me started on this topic.

**Comment by chess-levin** [comment]
So **Wifi & BT is not working together** on an ESP32: https://github.com/pschatzmann/ESP32-A2DP/wiki/WIFI-and-A2DP-Coexistence
